[package]
name = "magnet_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.17.0"
reqwest = "0.11.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
